[tool.poetry]
name = "protocol-compose"
version = "0.1.0"
description = ""
authors = ["jmfauvel <joaofauvel@fundacaomt.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
